codecov:
  token: "10582157-0990-491a-9bea-26b2926523f6"
  bot: "codecov-io"
  ci:
    - "github.com"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes

